### ISSUE TITLE
Is it possible to display a device screen to webpage.

### ISSUE THREAD

**Issue by Ankit9568** [arky/droidAtScreen#2]
Hi Team,

I am from RND team. I am some experiment on droid@Screen cast. i want to display device screen on webpage. Also I  have done R&D on showing swing application  on webpage. but experts says that is not right way. So is any way to shows device screen on webpage.

Thanks in advance 
Any help will be appreciated.

**Comment by arky** [comment]
Please kindly file supports request here:

https://github.com/ribomation/DroidAtScreen1
